services:
  stackupPostgres:
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stackup_postgress

  mongo:
    restart: always
    ports:
      - "127.0.0.1:27017:27017"

  rabbitmq:
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "127.0.0.1:8009:80"

  api-gateway:
    ports:
      - "127.0.0.1:3500:80"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__IdentityApiDatabase=host=stackupPostgres;Port=5432;Database=stackup_postgress;User Id=admin;Password=admin;"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings__ConnectionString=mongodb://mongo:27017"
      - "RabbitMQSettings__Host=rabbitmq"

  favorite-list-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "FavoriteListDatabaseSettings__ConnectionString=mongodb://mongo:27017"
      - "RabbitMQSettings__Host=rabbitmq"

volumes:
  stackup_postgres_data:
  pgadmin-data:
  dbdata6:
